###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/1000

###
DELETE http://localhost:3001/api/persons/6140042cd142b06b57ba25dc

###
DELETE http://localhost:3001/api/persons/1000

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Somebody",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ji",
    "number": "12345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "2"
}

###
PUT http://localhost:3001/api/persons/614003e0d142b06b57ba25d4
Content-Type: application/json

{
    "name": "Jack",
    "number": "2"
}